### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by mkeveney** [robotsrulz/MKS-TFT#4]
Do you have build/deploy instructions somewhere?  I couldn't find them.
Do you use the same boot loader as MKS (or some way to return to the original firmware)?

(Sorry for asking this in an 'issue' but I wasn't sure how else to contact you.  Very interested in the project!)

**Comment by robotsrulz** [comment]
Hi Matt!

Here are the short build instructions:

1. Download and install EmBitz 1.11.
2. Download and unpack the project to your local drive.
3. Open MKS-TFT32.ebp with EmBitz 1.11, select build target MKS-TFT32 and hit F7 (build project).
4. Firmware file is {ProjectDir}/bin/MKS-TFT32/MKS-TFT32.hex

Pre-built firmware file is {ProjectDir}/binaries/MKS-TFT32-for-testing-only.hex

You will need either ST-LINK v2 or Segger J-Link to flash the firmware to the board. Cheap ($2) chineese clones are okay for that.

If you want to fall back to Makerbase firmware I also uploaded original MKS-TFT32 bootloader (see {ProjectDir}/binaries/MKS-TFT32-factory-boot.hex). Flash the bootloader, then follow Makerbase instructions to update their firmware (put main firmware file and pictures to sd-card and boot the device).

**Comment by mkeveney** [comment]
Terrific!  Ordered an ST-LINK.  will let you know if I get stuck.
