### ISSUE TITLE
tft28

### ISSUE THREAD

**Issue by Tertius91820** [robotsrulz/MKS-TFT#6]
could it be possible to set up the mks config with 4 extruders?. I'm running a kraken.

**Comment by robotsrulz** [comment]
Yes, but it depends on main printer board firmware.

**Comment by cruwaller** [comment]
Mks fw support only 2 extruders. I asked this some weeks ago...

**Comment by robotsrulz** [comment]
I don't care about makerbase firmware

**Comment by cruwaller** [comment]
Oh sorry :( 
My bad. I didn't realize i wrote to different board... Sorry
